### ISSUE TITLE
Help Accessing MKR via MetaMask

### ISSUE THREAD

**Issue by jonathanmarcus** [makerdao/redeem#2]
Hello.

I have 1.06 MKR stored on an Ethereum address via MetaMask. I was able to redeem old MKR for new MKR.

![screen shot 2017-12-24 at 12 40 36 am](https://user-images.githubusercontent.com/1171361/34324494-4ad47cb8-e843-11e7-8211-a06afa9c65c9.png)

I want to send the MKR to a different Ethereum address, but when I connect to MyEtherWallet, my MKR balance displays 0.

![screen shot 2017-12-24 at 12 44 46 am](https://user-images.githubusercontent.com/1171361/34324508-b8201de0-e843-11e7-941e-2ae1bd497455.png)

Both Ethplorer and show a balance of 1.06 MKR:

https://ethplorer.io/address/0xff536328697859ec41b4f6a7e3a9cc3f372b0760
https://etherscan.io/address/0xff536328697859ec41b4f6a7e3a9cc3f372b0760#tokentxns

What should I do?

Thanks - Jonathan.

**Comment by nanexcool** [comment]
You need to add a Custom Token. Go to "View Wallet Info" then input the following:

address `0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2`
symbol `nuMKR`
decimals `18`

You cannot use `MKR` as a symbol since that's already taken by the old token.

![image](https://user-images.githubusercontent.com/52510/34361066-981332b8-ea45-11e7-9e6b-f755d2186ea1.png)

**Comment by jonathanmarcus** [comment]
You rule @nanexcool!! Thank you so much!! I had tried to create a custom token using that address, but didn't realize I needed to use a different symbol.
